services:
  ig-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - MODE=web
    image: ig-nonfollowers:web
    container_name: ig-nonfollowers-web
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ../data:/app/data
      # 掛載本機時區資訊到容器（Windows 上可能不適用，主要依賴 TZ 環境變數）
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
    ports:
      - "${PORT:-7860}:7860"

  ig-cli:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - MODE=cli
    image: ig-nonfollowers:cli
    environment:
      - TZ=Asia/Taipei
    stdin_open: true  # 開啟標準輸入
    tty: true        # 分配偽終端機
    volumes:
      - ../data:/app/data
      # 掛載本機時區資訊到容器（Windows 上可能不適用，主要依賴 TZ 環境變數）  
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
